version: '3.1'

services:
  db:
    image: postgres:12.4-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  api:
    container_name: api
    build:
      context: ./api_employee_management
      dockerfile: Dockerfile
    volumes:
      - /app/api/node_modules
      - ./api_employee_management:/app/api
    ports:
      - 3001:3001
  client:
    container_name: client
    build:
      context: ./client_employee_management
      dockerfile: Dockerfile
    volumes:
      - /app/client/node_modules
      - ./client_employee_management:/app/client
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  db: